Feat s3 transfermanager
awslabs/aws-sdk-kotlin pull request #651
Opened 2022-07-11 21:49 UTC by wty-Bryant

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-11 22:35 UTC, ianbotsf requested changes

2022-07-11 22:35 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
**Comment**: It looks like the return values from these methods are unused. I think that's right...we don't need them to create the top-level `Operation`. Given we're not using them, we don't need to create child `Operation` instances in these helper methods nor return anything from them.

2022-07-11 22:35 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt
> +
**Nit**: Can remove now.

2022-07-11 22:35 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/Operation.kt
>  // interface Operation: kotlinx.coroutines.Deferred<Unit> {
**Nit**: Can remove now.

2022-07-11 22:58 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +        val deferred = async {
Based on last comment, if we don't require helper function to return `Operation`, I agree we can delete such async in `uploadDirectory` method :)

2022-07-11 22:59 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/S3TransferManager.kt
> +
Sorry I forgot to delete it, I'll keep in mind later

2022-07-11 23:09 UTC, LDsBF commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
I also considered whether to keep them for later child `Operation` merging to parent `Operation` during progress listening and controlling. But as long as top level `Operation` can handle these requirement, I will remove them for now.

2022-07-12 03:06 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/DefaultS3TransferManager.kt
> +            }
That's an interesting idea. It may turn out that way but I'm not sure yet whether that'll be necessary/helpful. Until we actually need it, it's better to remove it. We can always add it back in later!

2022-07-12 03:06 UTC, ianbotsf commented on hlls/s3-transfermanager/jvm/src/aws/sdk/kotlin/s3/transfermanager/handler/Operation.kt
>  // interface Operation: kotlinx.coroutines.Deferred<Unit> {
Whoops, that's not quite what I meant. The _commented-out code_ should be removed but the `Operation` interface _definitely needs to implement_ `Deferred<Unit>`. Callers to S3TM's methods will receive an `Operation` back. It's implemented by `DefaultOperation` but they won't know that and they won't be able to access methods from `Deferred` unless those methods also exist on `Operation`.

2022-07-12 03:08 UTC, ianbotsf requested changes
Almost there, just a few minor changes and we can merge!

2022-07-12 15:14 UTC, lucix-aws approved these changes

2022-07-12 16:53 UTC, merged